sudo: false
language: go

go:
  - 1.3

install:
  - go get code.google.com/p/go.tools/cmd/goimports
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/tools/godep
  - go get code.google.com/p/go.tools/cmd/cover
